name: Release

permissions: write-all

on:
  push:
    tags:
      - v*.*.*

jobs:
  package:
    name: Package
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn install --frozen-lockfile
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - env:
          RAILS_ENV: production
          SECRET_KEY_BASE_DUMMY: 1
        run: |
          bin/rails assets:precompile release:package

  docker:
    name: Docker
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ghcr.io/bokoboshahni/eve_commerce
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=eve_commerce
            org.opencontainers.image.description=EVE Commerce provides a suite of tools for market analysis, trading, and procurement in EVE Online.
            org.opencontainers.image.vendor=Bokobo Shahni
            org.opencontainers.image.documentation=https://github.com/bokoboshahni/eve_commerce/blob/main/README.md
            org.opencontainers.image.source=https://github.com/bokoboshahni/eve_commerce/tree/main
            org.opencontainers.image.licenses=MIT
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            GIT_REF=${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
